// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/mptcp_message.proto

package bwnetflow.messages;

public final class MPTCPMessageProto {
  private MPTCPMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MPTCPMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:main.MPTCPMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string srcAddr = 1;</code>
     * @return The srcAddr.
     */
    java.lang.String getSrcAddr();
    /**
     * <code>string srcAddr = 1;</code>
     * @return The bytes for srcAddr.
     */
    com.google.protobuf.ByteString
        getSrcAddrBytes();

    /**
     * <code>string dstAddr = 2;</code>
     * @return The dstAddr.
     */
    java.lang.String getDstAddr();
    /**
     * <code>string dstAddr = 2;</code>
     * @return The bytes for dstAddr.
     */
    com.google.protobuf.ByteString
        getDstAddrBytes();

    /**
     * <code>uint32 srcPort = 3;</code>
     * @return The srcPort.
     */
    int getSrcPort();

    /**
     * <code>uint32 dstPort = 4;</code>
     * @return The dstPort.
     */
    int getDstPort();

    /**
     * <code>uint32 seqNum = 5;</code>
     * @return The seqNum.
     */
    int getSeqNum();

    /**
     * <code>int64 timestampCaptured = 6;</code>
     * @return The timestampCaptured.
     */
    long getTimestampCaptured();

    /**
     * <code>repeated string mptcpOptions = 7;</code>
     * @return A list containing the mptcpOptions.
     */
    java.util.List<java.lang.String>
        getMptcpOptionsList();
    /**
     * <code>repeated string mptcpOptions = 7;</code>
     * @return The count of mptcpOptions.
     */
    int getMptcpOptionsCount();
    /**
     * <code>repeated string mptcpOptions = 7;</code>
     * @param index The index of the element to return.
     * @return The mptcpOptions at the given index.
     */
    java.lang.String getMptcpOptions(int index);
    /**
     * <code>repeated string mptcpOptions = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the mptcpOptions at the given index.
     */
    com.google.protobuf.ByteString
        getMptcpOptionsBytes(int index);
  }
  /**
   * Protobuf type {@code main.MPTCPMessage}
   */
  public static final class MPTCPMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:main.MPTCPMessage)
      MPTCPMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MPTCPMessage.newBuilder() to construct.
    private MPTCPMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MPTCPMessage() {
      srcAddr_ = "";
      dstAddr_ = "";
      mptcpOptions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MPTCPMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MPTCPMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              srcAddr_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dstAddr_ = s;
              break;
            }
            case 24: {

              srcPort_ = input.readUInt32();
              break;
            }
            case 32: {

              dstPort_ = input.readUInt32();
              break;
            }
            case 40: {

              seqNum_ = input.readUInt32();
              break;
            }
            case 48: {

              timestampCaptured_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                mptcpOptions_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              mptcpOptions_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          mptcpOptions_ = mptcpOptions_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MPTCPMessageProto.internal_static_main_MPTCPMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MPTCPMessageProto.internal_static_main_MPTCPMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MPTCPMessageProto.MPTCPMessage.class, MPTCPMessageProto.MPTCPMessage.Builder.class);
    }

    public static final int SRCADDR_FIELD_NUMBER = 1;
    private volatile java.lang.Object srcAddr_;
    /**
     * <code>string srcAddr = 1;</code>
     * @return The srcAddr.
     */
    @java.lang.Override
    public java.lang.String getSrcAddr() {
      java.lang.Object ref = srcAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string srcAddr = 1;</code>
     * @return The bytes for srcAddr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSrcAddrBytes() {
      java.lang.Object ref = srcAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DSTADDR_FIELD_NUMBER = 2;
    private volatile java.lang.Object dstAddr_;
    /**
     * <code>string dstAddr = 2;</code>
     * @return The dstAddr.
     */
    @java.lang.Override
    public java.lang.String getDstAddr() {
      java.lang.Object ref = dstAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string dstAddr = 2;</code>
     * @return The bytes for dstAddr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDstAddrBytes() {
      java.lang.Object ref = dstAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRCPORT_FIELD_NUMBER = 3;
    private int srcPort_;
    /**
     * <code>uint32 srcPort = 3;</code>
     * @return The srcPort.
     */
    @java.lang.Override
    public int getSrcPort() {
      return srcPort_;
    }

    public static final int DSTPORT_FIELD_NUMBER = 4;
    private int dstPort_;
    /**
     * <code>uint32 dstPort = 4;</code>
     * @return The dstPort.
     */
    @java.lang.Override
    public int getDstPort() {
      return dstPort_;
    }

    public static final int SEQNUM_FIELD_NUMBER = 5;
    private int seqNum_;
    /**
     * <code>uint32 seqNum = 5;</code>
     * @return The seqNum.
     */
    @java.lang.Override
    public int getSeqNum() {
      return seqNum_;
    }

    public static final int TIMESTAMPCAPTURED_FIELD_NUMBER = 6;
    private long timestampCaptured_;
    /**
     * <code>int64 timestampCaptured = 6;</code>
     * @return The timestampCaptured.
     */
    @java.lang.Override
    public long getTimestampCaptured() {
      return timestampCaptured_;
    }

    public static final int MPTCPOPTIONS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList mptcpOptions_;
    /**
     * <code>repeated string mptcpOptions = 7;</code>
     * @return A list containing the mptcpOptions.
     */
    public com.google.protobuf.ProtocolStringList
        getMptcpOptionsList() {
      return mptcpOptions_;
    }
    /**
     * <code>repeated string mptcpOptions = 7;</code>
     * @return The count of mptcpOptions.
     */
    public int getMptcpOptionsCount() {
      return mptcpOptions_.size();
    }
    /**
     * <code>repeated string mptcpOptions = 7;</code>
     * @param index The index of the element to return.
     * @return The mptcpOptions at the given index.
     */
    public java.lang.String getMptcpOptions(int index) {
      return mptcpOptions_.get(index);
    }
    /**
     * <code>repeated string mptcpOptions = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the mptcpOptions at the given index.
     */
    public com.google.protobuf.ByteString
        getMptcpOptionsBytes(int index) {
      return mptcpOptions_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSrcAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, srcAddr_);
      }
      if (!getDstAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dstAddr_);
      }
      if (srcPort_ != 0) {
        output.writeUInt32(3, srcPort_);
      }
      if (dstPort_ != 0) {
        output.writeUInt32(4, dstPort_);
      }
      if (seqNum_ != 0) {
        output.writeUInt32(5, seqNum_);
      }
      if (timestampCaptured_ != 0L) {
        output.writeInt64(6, timestampCaptured_);
      }
      for (int i = 0; i < mptcpOptions_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, mptcpOptions_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSrcAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, srcAddr_);
      }
      if (!getDstAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dstAddr_);
      }
      if (srcPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, srcPort_);
      }
      if (dstPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, dstPort_);
      }
      if (seqNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, seqNum_);
      }
      if (timestampCaptured_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestampCaptured_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < mptcpOptions_.size(); i++) {
          dataSize += computeStringSizeNoTag(mptcpOptions_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMptcpOptionsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MPTCPMessageProto.MPTCPMessage)) {
        return super.equals(obj);
      }
      MPTCPMessageProto.MPTCPMessage other = (MPTCPMessageProto.MPTCPMessage) obj;

      if (!getSrcAddr()
          .equals(other.getSrcAddr())) return false;
      if (!getDstAddr()
          .equals(other.getDstAddr())) return false;
      if (getSrcPort()
          != other.getSrcPort()) return false;
      if (getDstPort()
          != other.getDstPort()) return false;
      if (getSeqNum()
          != other.getSeqNum()) return false;
      if (getTimestampCaptured()
          != other.getTimestampCaptured()) return false;
      if (!getMptcpOptionsList()
          .equals(other.getMptcpOptionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SRCADDR_FIELD_NUMBER;
      hash = (53 * hash) + getSrcAddr().hashCode();
      hash = (37 * hash) + DSTADDR_FIELD_NUMBER;
      hash = (53 * hash) + getDstAddr().hashCode();
      hash = (37 * hash) + SRCPORT_FIELD_NUMBER;
      hash = (53 * hash) + getSrcPort();
      hash = (37 * hash) + DSTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getDstPort();
      hash = (37 * hash) + SEQNUM_FIELD_NUMBER;
      hash = (53 * hash) + getSeqNum();
      hash = (37 * hash) + TIMESTAMPCAPTURED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampCaptured());
      if (getMptcpOptionsCount() > 0) {
        hash = (37 * hash) + MPTCPOPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getMptcpOptionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MPTCPMessageProto.MPTCPMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MPTCPMessageProto.MPTCPMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MPTCPMessageProto.MPTCPMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MPTCPMessageProto.MPTCPMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MPTCPMessageProto.MPTCPMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code main.MPTCPMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:main.MPTCPMessage)
        MPTCPMessageProto.MPTCPMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MPTCPMessageProto.internal_static_main_MPTCPMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MPTCPMessageProto.internal_static_main_MPTCPMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MPTCPMessageProto.MPTCPMessage.class, MPTCPMessageProto.MPTCPMessage.Builder.class);
      }

      // Construct using bwnetflow.messages.MPTCPMessageProto.MPTCPMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        srcAddr_ = "";

        dstAddr_ = "";

        srcPort_ = 0;

        dstPort_ = 0;

        seqNum_ = 0;

        timestampCaptured_ = 0L;

        mptcpOptions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MPTCPMessageProto.internal_static_main_MPTCPMessage_descriptor;
      }

      @java.lang.Override
      public MPTCPMessageProto.MPTCPMessage getDefaultInstanceForType() {
        return MPTCPMessageProto.MPTCPMessage.getDefaultInstance();
      }

      @java.lang.Override
      public MPTCPMessageProto.MPTCPMessage build() {
        MPTCPMessageProto.MPTCPMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MPTCPMessageProto.MPTCPMessage buildPartial() {
        MPTCPMessageProto.MPTCPMessage result = new MPTCPMessageProto.MPTCPMessage(this);
        int from_bitField0_ = bitField0_;
        result.srcAddr_ = srcAddr_;
        result.dstAddr_ = dstAddr_;
        result.srcPort_ = srcPort_;
        result.dstPort_ = dstPort_;
        result.seqNum_ = seqNum_;
        result.timestampCaptured_ = timestampCaptured_;
        if (((bitField0_ & 0x00000001) != 0)) {
          mptcpOptions_ = mptcpOptions_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.mptcpOptions_ = mptcpOptions_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MPTCPMessageProto.MPTCPMessage) {
          return mergeFrom((MPTCPMessageProto.MPTCPMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MPTCPMessageProto.MPTCPMessage other) {
        if (other == MPTCPMessageProto.MPTCPMessage.getDefaultInstance()) return this;
        if (!other.getSrcAddr().isEmpty()) {
          srcAddr_ = other.srcAddr_;
          onChanged();
        }
        if (!other.getDstAddr().isEmpty()) {
          dstAddr_ = other.dstAddr_;
          onChanged();
        }
        if (other.getSrcPort() != 0) {
          setSrcPort(other.getSrcPort());
        }
        if (other.getDstPort() != 0) {
          setDstPort(other.getDstPort());
        }
        if (other.getSeqNum() != 0) {
          setSeqNum(other.getSeqNum());
        }
        if (other.getTimestampCaptured() != 0L) {
          setTimestampCaptured(other.getTimestampCaptured());
        }
        if (!other.mptcpOptions_.isEmpty()) {
          if (mptcpOptions_.isEmpty()) {
            mptcpOptions_ = other.mptcpOptions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMptcpOptionsIsMutable();
            mptcpOptions_.addAll(other.mptcpOptions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MPTCPMessageProto.MPTCPMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MPTCPMessageProto.MPTCPMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object srcAddr_ = "";
      /**
       * <code>string srcAddr = 1;</code>
       * @return The srcAddr.
       */
      public java.lang.String getSrcAddr() {
        java.lang.Object ref = srcAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          srcAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string srcAddr = 1;</code>
       * @return The bytes for srcAddr.
       */
      public com.google.protobuf.ByteString
          getSrcAddrBytes() {
        java.lang.Object ref = srcAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srcAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srcAddr = 1;</code>
       * @param value The srcAddr to set.
       * @return This builder for chaining.
       */
      public Builder setSrcAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srcAddr = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcAddr() {
        
        srcAddr_ = getDefaultInstance().getSrcAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string srcAddr = 1;</code>
       * @param value The bytes for srcAddr to set.
       * @return This builder for chaining.
       */
      public Builder setSrcAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srcAddr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dstAddr_ = "";
      /**
       * <code>string dstAddr = 2;</code>
       * @return The dstAddr.
       */
      public java.lang.String getDstAddr() {
        java.lang.Object ref = dstAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dstAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dstAddr = 2;</code>
       * @return The bytes for dstAddr.
       */
      public com.google.protobuf.ByteString
          getDstAddrBytes() {
        java.lang.Object ref = dstAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dstAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dstAddr = 2;</code>
       * @param value The dstAddr to set.
       * @return This builder for chaining.
       */
      public Builder setDstAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dstAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dstAddr = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDstAddr() {
        
        dstAddr_ = getDefaultInstance().getDstAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string dstAddr = 2;</code>
       * @param value The bytes for dstAddr to set.
       * @return This builder for chaining.
       */
      public Builder setDstAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dstAddr_ = value;
        onChanged();
        return this;
      }

      private int srcPort_ ;
      /**
       * <code>uint32 srcPort = 3;</code>
       * @return The srcPort.
       */
      @java.lang.Override
      public int getSrcPort() {
        return srcPort_;
      }
      /**
       * <code>uint32 srcPort = 3;</code>
       * @param value The srcPort to set.
       * @return This builder for chaining.
       */
      public Builder setSrcPort(int value) {
        
        srcPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 srcPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcPort() {
        
        srcPort_ = 0;
        onChanged();
        return this;
      }

      private int dstPort_ ;
      /**
       * <code>uint32 dstPort = 4;</code>
       * @return The dstPort.
       */
      @java.lang.Override
      public int getDstPort() {
        return dstPort_;
      }
      /**
       * <code>uint32 dstPort = 4;</code>
       * @param value The dstPort to set.
       * @return This builder for chaining.
       */
      public Builder setDstPort(int value) {
        
        dstPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 dstPort = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDstPort() {
        
        dstPort_ = 0;
        onChanged();
        return this;
      }

      private int seqNum_ ;
      /**
       * <code>uint32 seqNum = 5;</code>
       * @return The seqNum.
       */
      @java.lang.Override
      public int getSeqNum() {
        return seqNum_;
      }
      /**
       * <code>uint32 seqNum = 5;</code>
       * @param value The seqNum to set.
       * @return This builder for chaining.
       */
      public Builder setSeqNum(int value) {
        
        seqNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 seqNum = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeqNum() {
        
        seqNum_ = 0;
        onChanged();
        return this;
      }

      private long timestampCaptured_ ;
      /**
       * <code>int64 timestampCaptured = 6;</code>
       * @return The timestampCaptured.
       */
      @java.lang.Override
      public long getTimestampCaptured() {
        return timestampCaptured_;
      }
      /**
       * <code>int64 timestampCaptured = 6;</code>
       * @param value The timestampCaptured to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampCaptured(long value) {
        
        timestampCaptured_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestampCaptured = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampCaptured() {
        
        timestampCaptured_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList mptcpOptions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMptcpOptionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          mptcpOptions_ = new com.google.protobuf.LazyStringArrayList(mptcpOptions_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @return A list containing the mptcpOptions.
       */
      public com.google.protobuf.ProtocolStringList
          getMptcpOptionsList() {
        return mptcpOptions_.getUnmodifiableView();
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @return The count of mptcpOptions.
       */
      public int getMptcpOptionsCount() {
        return mptcpOptions_.size();
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @param index The index of the element to return.
       * @return The mptcpOptions at the given index.
       */
      public java.lang.String getMptcpOptions(int index) {
        return mptcpOptions_.get(index);
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the mptcpOptions at the given index.
       */
      public com.google.protobuf.ByteString
          getMptcpOptionsBytes(int index) {
        return mptcpOptions_.getByteString(index);
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @param index The index to set the value at.
       * @param value The mptcpOptions to set.
       * @return This builder for chaining.
       */
      public Builder setMptcpOptions(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMptcpOptionsIsMutable();
        mptcpOptions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @param value The mptcpOptions to add.
       * @return This builder for chaining.
       */
      public Builder addMptcpOptions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMptcpOptionsIsMutable();
        mptcpOptions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @param values The mptcpOptions to add.
       * @return This builder for chaining.
       */
      public Builder addAllMptcpOptions(
          java.lang.Iterable<java.lang.String> values) {
        ensureMptcpOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mptcpOptions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMptcpOptions() {
        mptcpOptions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mptcpOptions = 7;</code>
       * @param value The bytes of the mptcpOptions to add.
       * @return This builder for chaining.
       */
      public Builder addMptcpOptionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMptcpOptionsIsMutable();
        mptcpOptions_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:main.MPTCPMessage)
    }

    // @@protoc_insertion_point(class_scope:main.MPTCPMessage)
    private static final MPTCPMessageProto.MPTCPMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MPTCPMessageProto.MPTCPMessage();
    }

    public static MPTCPMessageProto.MPTCPMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MPTCPMessage>
        PARSER = new com.google.protobuf.AbstractParser<MPTCPMessage>() {
      @java.lang.Override
      public MPTCPMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MPTCPMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MPTCPMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MPTCPMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MPTCPMessageProto.MPTCPMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_main_MPTCPMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_main_MPTCPMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/mptcp_message.proto\022\004main\"\223\001\n\014MP" +
      "TCPMessage\022\017\n\007srcAddr\030\001 \001(\t\022\017\n\007dstAddr\030\002" +
      " \001(\t\022\017\n\007srcPort\030\003 \001(\r\022\017\n\007dstPort\030\004 \001(\r\022\016" +
      "\n\006seqNum\030\005 \001(\r\022\031\n\021timestampCaptured\030\006 \001(" +
      "\003\022\024\n\014mptcpOptions\030\007 \003(\tB?\n\tbwnetflowB\021MP" +
      "TCPMessageProtoZ\037github.com/protobuf/typ" +
      "es/mptcpb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_main_MPTCPMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_main_MPTCPMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_main_MPTCPMessage_descriptor,
        new java.lang.String[] { "SrcAddr", "DstAddr", "SrcPort", "DstPort", "SeqNum", "TimestampCaptured", "MptcpOptions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
